name = "transport-guidesign-generator"
main = "workers/src/index.js"
compatibility_date = "2024-01-01"

# Uncomment to use KV, Durable Objects, or other bindings
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Uncomment to add environment variables
# [vars]
# MY_VAR = "production"
